const { assessCase } = require("./decisionEngine");

const express = require("express");
const cors = require("cors");

const app = express();
app.use(cors());
app.use(express.json());

// Health check
app.get("/health", (req, res) => {
  res.json({ status: "ok" });
});

// MVP endpoint: receive a case and return a mock assessment
app.post("/cases", (req, res) => {
  const payload = req.body;

  // Minimal validation
  if (!payload.pathway || !payload.chief_concern) {
    return res.status(400).json({
      error: "Missing required fields: pathway and chief_concern"
    });
  }

  // Mock response (later this will be generated by decision rules)
  const assessment = assessCase(payload);
  res.json(assessment);
});

const PORT = process.env.PORT || 3001;
app.listen(PORT, () => {
  console.log(`API running on http://localhost:${PORT}`);
});
